// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qlepahvfmfenmsaeyjug.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFsZXBhaHZmbWZlbm1zYWV5anVnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxMDQyOTAsImV4cCI6MjA2MzY4MDI5MH0.8ZGSkrCZ8OdiTapfgwVZJrw4r4Ofk2pNukUhOBdgqRk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);